## Quiz on 1D Numpy Array


Implement the following vector subtraction in numpy: u-v


In [38]:
import numpy as np
u = np.array([1, 0])
v = np.array([0, 1])

result=u-v
print("Result =",result)

Result = [ 1 -1]


<hr>


Multiply the numpy array z with -2:


In [37]:
z = np.array([2, 4])
z=z*-2
print("Result =",z)

Result = [-4 -8]


<hr>


Consider the list <code>\[1, 2, 3, 4, 5]</code> and <code>\[1, 0, 1, 0, 1]</code>. Cast both lists to a numpy array then multiply them together:


In [16]:
list1=np.array([1, 2, 3, 4, 5])
list2=np.array([1, 0, 1, 0, 1])
result=list1*list2
print("Result =",result)

Result = [1 0 3 0 5]


<hr>


Convert the list <code>\[1, 2, 3]</code> and <code>\[8, 9, 10]</code> to numpy arrays <code>arr1</code> and <code>arr2</code>. Then perform <code>Addition</code> , <code>Subtraction</code> , <code>Multiplication</code> , <code>Division</code> and <code>Dot Operation</code> on the <code>arr1</code> and <code>arr2</code>.



In [36]:
import numpy as np
arr1=np.array([1, 2, 3])
arr2=np.array([8, 9, 10])

Add=np.add(arr1,arr2)
Sub=np.subtract(arr1,arr2)
Mul=np.multiply(arr1,arr2)
Div=np.divide(arr1,arr2)
Dot=np.dot(arr1,arr2)
print("All Operation Result : ")
print("Addition =",Add)
print("Subtraction =",Sub)
print("Multiplication =",Mul)
print("Division =",Div)
print("Dot Operation =",Dot)

All Operation Result : 
Addition = [ 9 11 13]
Subtraction = [-7 -7 -7]
Multiplication = [ 8 18 30]
Division = [0.125      0.22222222 0.3       ]
Dot Operation = 56


Convert the list <code>\[1, 2, 3, 4, 5]</code> and <code>\[6, 7, 8, 9, 10]</code> to numpy arrays <code>arr1</code> and <code>arr2</code>. Then find the even and odd numbers from <code>arr1</code> and <code>arr2</code>.


In [19]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

even_1 = arr1[1:5:2]
print("Even element from array1 =",even_1)

odd_1=arr1[0:5:2]
print("Odd element from array1 =",odd_1)

even_2 = arr2[0:5:2]
print("Even element from array2 =",even_2)
    
odd_2=arr2[1:5:2]
print("Odd element from array2 =",odd_2)

Even element from array1 = [2 4]
Odd element from array1 = [1 3 5]
Even element from array2 = [ 6  8 10]
Odd element from array2 = [7 9]


<h2>Quiz on 2D Numpy Array</h2>


Consider the following list <code>a</code>, convert it to Numpy Array.


In [21]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

arr=np.array(a)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Calculate the numpy array size.


In [23]:
length=arr.size
print(length)

12


Access the element on the first row and first and second columns.


In [25]:
arr[0][0:2]

array([1, 2])

Perform matrix multiplication with the numpy arrays <code>A</code> and <code>B</code>.


In [33]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
result=np.dot(A,B)
print("Result matrix multiplication: \n",result)

Result matrix multiplication: 
 [[ 1  4]
 [ 5 12]
 [ 9 20]]
